# Use an official Node runtime as the base image
FROM node:20-alpine

# for local testing
ENV PORT=5000 

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY DiffSentry/package*.json ./

# Install project dependencies
RUN npm ci

# Copy the rest of the application code
COPY DiffSentry/ .

# Build the application
RUN npm run build

# Create a production-ready server setup
RUN npm install -g serve

# Expose the port that Heroku will use
EXPOSE $PORT

# Define the command to run the app
# Use the $PORT environment variable that Heroku provides
CMD serve -s dist -l $PORT